set(CLAW3D_APP_HEADERS
    viewport/viewport_canvas.h
    product_identity.h
    bootstrap/app_launcher.h
    bootstrap/app_config.h
    bootstrap/imgui_runtime.h
    window/main_window.h
    dialogs/imgui_dialogs.h
    dialogs/scope.h
    dialogs/basic_dialogs.h
    dialogs/alpha_wrap_dialog.h
    dialogs/ransac_dialog.h
    dialogs/region_growing_dialog.h
    dialogs/cgal_simplification_dialog.h
    dialogs/acvd_dialog.h
    dialogs/vsa_dialog.h
    dialogs/planar_patch_remeshing_dialog.h
    dialogs/cgal_smoothing_dialog.h
    dialogs/geodesic_distance_dialog.h
    dialogs/mcf_skeletonization_dialog.h
    dialogs/arap_deformation_dialog.h
    dialogs/parameterization_dialog.h
    dialogs/3d_generation_dialog.h
    dialogs/measurement_dialog.h
    widgets/imgui_widgets.h
    ai/ai_chat.h
    ai/ai_context.h
    ../common/acvd_contract.h
    ../common/http_status.h
    ../common/preview_policy.h
    ../common/primitive_preview_policy.h
    ../common/alpha_wrap_contract.h
    ../common/arap_deformation_contract.h
    ../common/geodesic_contract.h
    ../common/mcf_skeletonization_contract.h
    ../common/parameterization_contract.h
    ../common/ransac_contract.h
    ../common/region_growing_contract.h
    ../common/planar_patch_remeshing_contract.h
    ../common/simplification_contract.h
    ../common/smoothing_contract.h
    ../common/vsa_contract.h
    ui/panel_help.h
    ui/colormap.h
    ui/layout_helpers.h
    ui/status_widgets.h
    platform/clipboard.h
    platform/runtime_probe.h
    platform/window_events.h
    selection/selection_manager.h
    dialogs/crop_dialog.h
    dialogs/align_dialog.h
    dialogs/animation_dialog.h
    history/operation_history.h
    ui/ui_scale.h
    ui/ui_frame_gate.h
    dialogs/prerequisites.h
    util/thread_priority.h
    ai/ai_widget.h
    ai/ai_service.h
    ai/ai_language.h
    ai/ai_prompt_utils.h
    ai/mesh_ai_stats.h
    overlays/overlay_utils.h
    overlays/overlay_controller.h
    overlays/overlay_palette.h
    overlays/region_growing_overlay_types.h
    overlays/algorithm_overlay_state.h
    overlays/interaction_overlay_state.h
    window/window_helpers.h
    menus/ai_menu_utils.h
    ai/ai_explainable_item.h
    viewport/input_math.h
    viewport/gizmo_constants.h
)

set(CLAW3D_APP_SOURCES
    ../main.cpp
    bootstrap/app_launcher.cpp
    bootstrap/app_config.cpp
    bootstrap/imgui_runtime.cpp
    viewport/viewport_canvas.cpp
    viewport/camera.cpp
    viewport/models.cpp
    viewport/axes.cpp
    viewport/render.cpp
    viewport/viewport_panel.cpp
    viewport/selection_bbox.cpp
    viewport/lifecycle.cpp
    viewport/input.cpp
    viewport/drag.cpp
    viewport/selection_picking.cpp
    viewport/measurement_picking.cpp
    viewport/gizmo_picking.cpp
    window/main_window.cpp
    dialogs/utility_dialogs.cpp
    dialogs/poisson_dialog.cpp
    dialogs/distance_dialogs.cpp
    dialogs/properties_dialog.cpp
    dialogs/surface_mesh_basic_dialogs.cpp
    dialogs/point_cloud_basic_dialogs.cpp
    dialogs/alpha_wrap_dialog.cpp
    dialogs/ransac_dialog.cpp
    dialogs/region_growing_dialog.cpp
    dialogs/cgal_simplification_dialog.cpp
    dialogs/acvd_dialog.cpp
    dialogs/vsa_dialog.cpp
    dialogs/planar_patch_remeshing_dialog.cpp
    dialogs/cgal_smoothing_dialog.cpp
    dialogs/geodesic_distance_dialog.cpp
    dialogs/mcf_skeletonization_dialog.cpp
    dialogs/arap_deformation_dialog.cpp
    dialogs/parameterization_dialog.cpp
    dialogs/3d_generation_dialog.cpp
    dialogs/measurement_dialog.cpp
    widgets/attribute_manager.cpp
    widgets/model_utils.cpp
    widgets/model_list.cpp
    widgets/imgui_widgets.cpp
    widgets/log.cpp
    widgets/health_report.cpp
    widgets/history.cpp
    widgets/settings.cpp
    ui/colormap.cpp
    ui/walk_through.cpp
    platform/clipboard.cpp
    platform/runtime_probe.cpp
    platform/window_events.cpp
    ai/ai_chat.cpp
    ai/ai_context.cpp
    ui/panel_help.cpp
    selection/selection_manager.cpp
    dialogs/crop_dialog.cpp
    dialogs/align_dialog.cpp
    dialogs/animation_dialog.cpp
    history/operation_history.cpp
    ui/ui_scale.cpp
    dialogs/prerequisites.cpp
    util/thread_priority.cpp
    ai/ai_widget.cpp
    ai/ai_service.cpp
    ai/ai_explainable_item.cpp
    ai/ai_language.cpp
    ai/ai_prompt_utils.cpp
    ai/mesh_ai_stats.cpp
    overlays/overlay_utils.cpp
    overlays/overlay_controller.cpp
    window/file_actions.cpp
    window/ai_chat_panel.cpp
    window/algorithm_results.cpp
    window/dialog_dispatch.cpp
    window/runtime.cpp
    window/runtime_ui.cpp
    window/layout.cpp
    window/window_helpers.cpp
    menus/ai_menu_utils.cpp
    menus/ai_help_menu.cpp
    menus/analysis_menu.cpp
    menus/align_menu.cpp
    menus/crop_clip_menu.cpp
    menus/edit_menu.cpp
    menus/measurement_menu.cpp
    menus/point_cloud_menu.cpp
    menus/point_cloud_triangulation_menu.cpp
    menus/property_menu.cpp
    menus/select_menu.cpp
    menus/surface_mesh_menu.cpp
    menus/surface_mesh_processing_menu.cpp
    menus/surface_mesh_repair_menu.cpp
    menus/surface_mesh_topology_menu.cpp
    menus/view_camera_menu.cpp
    selection/selection_queries.cpp
    selection/extract_selection.cpp
    selection/delete_selection.cpp
    overlays/measurement_overlay.cpp
    overlays/crop_overlay.cpp
    overlays/align_overlay.cpp
    overlays/selection_overlays.cpp
    overlays/ransac_overlay.cpp
    overlays/region_growing_overlay.cpp
    overlays/alpha_wrap_overlay.cpp
    overlays/simplification_overlay.cpp
    overlays/acvd_overlay.cpp
    overlays/vsa_overlay.cpp
    overlays/ppr_overlay.cpp
    overlays/smoothing_overlay.cpp
    overlays/mcf_overlay.cpp
    overlays/geodesic_overlay.cpp
    overlays/geodesic_front_overlay.cpp
    overlays/geodesic_path_overlay.cpp
    overlays/arap_overlay.cpp
    overlays/arap_preview_overlay.cpp
    overlays/algorithm_overlays.cpp
    menus/menu_bar.cpp
)
